import sys
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from datetime import datetime, timezone

# Add the parent directory to sys.path to import app
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import models

# Database Configuration
REMOTE_URL = "postgresql://postgres:zjRYAsATFmvPlnQOZruilNIwwEBZcmyU@crossover.proxy.rlwy.net:29288/railway"
LOCAL_URL = "postgresql://space_user:space_password@localhost:5433/space_db"

def seed_db(db_url, label):
    print(f"\n--- Seeding {label} Database ---")
    
    # Set environment variable because app.database expects it
    os.environ["DATABASE_URL"] = db_url
    
    # Import models here to ensure the env var is picked up if needed (though we use create_engine directly)
    from app import models
    
    # Create engine for target DB
    try:
        engine = create_engine(db_url)
        Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)
        db = Session()
        
        print(f"Connecting to {label} database...")
        # Create table if it doesn't exist
        models.Base.metadata.create_all(bind=engine)
        
        # Get existing slugs to avoid duplicates
        existing_slugs = [s[0] for s in db.query(models.MediaSource.slug).all()]


        """
        CAMPOS DE MEDIA_SOURCE:
        - slug: Identificador único (URL friendly).
        - category: Clasificación principal. 
            Valores: 'portal', 'youtube', 'news', 'podcast', 'agency', 'education', 'other'
        - subcategory: Sub-clasificación temática.
            Valores sugeridos: 'divulgacion', 'industria', 'tecnico', 'noticias', 'global', 'newsletter'
        - language: Idioma principal ('es', 'en', 'multi').
        - country / country_name: Localización del recurso.
        - name: Nombre visible.
        - description / description_en: Resumen en español e inglés.
        - rating: Importancia (1-5).
        - recommended: Flag para destacar.
        - difficulty: Nivel de entrada.
            Valores: 'general', 'intermedio', 'avanzado', 'experto'
        - website / youtube_url / etc: Enlaces a plataformas.
        - content_format / topics: Listas JSON de etiquetas de contenido.
        - featured: Si aparece en secciones destacadas.
        """
        media_data = [
 
    # ── ENGLISH CHANNELS ──────────────────────────────────────────────────────
 
    {
        "slug": "everyday-astronaut",
        "category": "youtube",
        "subcategory": "industria",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Everyday Astronaut",
        "description": "Tim Dodd explica conceptos complejos de ingeniería aeroespacial de forma comprensible para todos.",
        "description_en": "Tim Dodd explains complex aerospace engineering concepts in a way anyone can understand.",
        "tagline": "Bringing Space Down To Earth",
        "tagline_en": "Bringing Space Down To Earth",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "website": "https://everydayastronaut.com",
        "youtube_url": "https://www.youtube.com/@EverydayAstronaut",
        "youtube_handle": "@EverydayAstronaut",
        "content_format": ["video", "article", "livestream"],
        "topics": ["engineering", "engines", "starship", "history", "spaceflight"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "scott-manley",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Scott Manley",
        "description": "Astrofísico y piloto que explica astronomía, física y la industria espacial con rigor técnico y buen humor.",
        "description_en": "Astrophysicist and pilot covering astronomy, physics, and the space industry with technical depth and humor.",
        "tagline": "Fly Safe!",
        "tagline_en": "Fly Safe!",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@scottmanley",
        "youtube_handle": "@scottmanley",
        "content_format": ["video"],
        "topics": ["astronomy", "rockets", "physics", "history", "spaceflight", "games"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "marcus-house",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "AU",
        "country_name": "Australia",
        "name": "Marcus House",
        "description": "Resúmenes semanales de noticias espaciales con foco en SpaceX, con animaciones y análisis propios.",
        "description_en": "Weekly space news summaries focused on SpaceX, featuring original animations and analysis.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@MarcusHouse",
        "youtube_handle": "@MarcusHouse",
        "content_format": ["video"],
        "topics": ["spacex", "starship", "news", "launch"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "matt-lowne",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Matt Lowne",
        "description": "Divulgación espacial y contenido de Kerbal Space Program; mezcla entretenimiento con conceptos de astrodinámica.",
        "description_en": "Space science content and Kerbal Space Program; blends entertainment with astrodynamics concepts.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@MattLowne",
        "youtube_handle": "@MattLowne",
        "content_format": ["video"],
        "topics": ["KSP", "spaceflight", "gaming", "divulgacion"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "anton-petrov",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Anton Petrov",
        "description": "Noticias científicas diarias sobre astronomía, física y cosmología presentadas de forma accesible.",
        "description_en": "Daily science news covering astronomy, physics, and cosmology in an accessible format.",
        "tagline": "Hello, wonderful person!",
        "tagline_en": "Hello, wonderful person!",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@whatdamath",
        "youtube_handle": "@whatdamath",
        "content_format": ["video"],
        "topics": ["astronomy", "cosmology", "physics", "news"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "fraser-cain",
        "category": "youtube",
        "subcategory": "global",
        "language": "en",
        "country": "CA",
        "country_name": "Canada",
        "name": "Fraser Cain",
        "description": "Editor de Universe Today; cubre astronomía, exploración espacial y noticias científicas.",
        "description_en": "Publisher of Universe Today; covers astronomy, space exploration, and science news.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "website": "https://www.universetoday.com",
        "youtube_url": "https://www.youtube.com/@frasercain",
        "youtube_handle": "@frasercain",
        "content_format": ["video", "article"],
        "topics": ["astronomy", "cosmology", "news", "space exploration"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "john-michael-godier",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "John Michael Godier",
        "description": "Ensayos especulativos y divulgación sobre el universo, la vida extraterrestre y el futuro de la humanidad.",
        "description_en": "Speculative essays and science communication on the universe, extraterrestrial life, and humanity's future.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@JohnMichaelGodier",
        "youtube_handle": "@JohnMichaelGodier",
        "content_format": ["video"],
        "topics": ["fermi paradox", "astrobiology", "SETI", "cosmology"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "isaac-arthur",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Isaac Arthur",
        "description": "Análisis en profundidad del futuro de la humanidad: megaestructuras, colonización espacial y civilizaciones avanzadas.",
        "description_en": "In-depth analysis of humanity's future: megastructures, space colonization, and advanced civilizations.",
        "tagline": "Science & Futurism",
        "tagline_en": "Science & Futurism",
        "rating": 5,
        "recommended": True,
        "difficulty": "avanzado",
        "website": "https://www.isaacarthur.net",
        "youtube_url": "https://www.youtube.com/@isaacarthurSFIA",
        "youtube_handle": "@isaacarthurSFIA",
        "content_format": ["video", "podcast"],
        "topics": ["megastructures", "colonization", "futurism", "Dyson sphere", "Fermi paradox"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "veritasium",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Veritasium",
        "description": "Derek Muller presenta ciencia, matemáticas e ingeniería con experimentos sorprendentes y narrativa impecable.",
        "description_en": "Derek Muller presents science, math, and engineering through surprising experiments and compelling storytelling.",
        "tagline": "An element of truth",
        "tagline_en": "An element of truth",
        "rating": 5,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@veritasium",
        "youtube_handle": "@veritasium",
        "content_format": ["video"],
        "topics": ["physics", "mathematics", "engineering", "experiments"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "vsauce",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Vsauce",
        "description": "Michael Stevens explora preguntas filosóficas, científicas y matemáticas de manera profunda y entretenida.",
        "description_en": "Michael Stevens explores philosophical, scientific, and mathematical questions in a deep and entertaining way.",
        "tagline": "Curiosity is the spark",
        "tagline_en": "Curiosity is the spark",
        "rating": 5,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@Vsauce",
        "youtube_handle": "@Vsauce",
        "content_format": ["video"],
        "topics": ["curiosity", "philosophy", "physics", "mathematics", "psychology"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "smarter-every-day",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "SmarterEveryDay",
        "description": "Destin Sandlin explora el mundo mediante slow-motion, ciencia aplicada e ingeniería de forma curiosa y familiar.",
        "description_en": "Destin Sandlin explores the world through slow-motion, applied science, and engineering in a curious, family-friendly way.",
        "tagline": "Getting smarter every day",
        "tagline_en": "Getting smarter every day",
        "rating": 5,
        "recommended": True,
        "difficulty": "general",
        "website": "https://www.smartereveryday.com",
        "youtube_url": "https://www.youtube.com/@smartereveryday",
        "youtube_handle": "@smartereveryday",
        "content_format": ["video"],
        "topics": ["slow-motion", "engineering", "physics", "biology", "military"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "physics-girl",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Physics Girl",
        "description": "Dianna Cowern divulga física con experimentos visuales accesibles y emocionantes.",
        "description_en": "Dianna Cowern communicates physics through visually accessible and exciting experiments.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@physicsgirl",
        "youtube_handle": "@physicsgirl",
        "content_format": ["video"],
        "topics": ["physics", "experiments", "education"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "real-engineering",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "IE",
        "country_name": "Ireland",
        "name": "Real Engineering",
        "description": "Análisis técnico de ingeniería aeroespacial, infraestructuras y tecnología con animaciones de alta calidad.",
        "description_en": "Technical analysis of aerospace engineering, infrastructure, and technology with high-quality animations.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@RealEngineering",
        "youtube_handle": "@RealEngineering",
        "content_format": ["video"],
        "topics": ["aerospace", "engineering", "technology", "infrastructure"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "the-angry-astronaut",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "The Angry Astronaut",
        "description": "Comentario crítico y noticias sobre SpaceX, NASA y la industria espacial comercial.",
        "description_en": "Critical commentary and news on SpaceX, NASA, and the commercial space industry.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@TheAngryAstronaut",
        "youtube_handle": "@TheAngryAstronaut",
        "content_format": ["video"],
        "topics": ["SpaceX", "NASA", "news", "opinion"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "what-about-it",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "DE",
        "country_name": "Germany",
        "name": "What about it!?",
        "description": "Análisis detallado de SpaceX y otros programas espaciales, con foco en ingeniería y estrategia empresarial.",
        "description_en": "Detailed analysis of SpaceX and other space programs, focusing on engineering and business strategy.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@WhatAboutIt",
        "youtube_handle": "@WhatAboutIt",
        "content_format": ["video"],
        "topics": ["SpaceX", "Starship", "analysis", "engineering"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "ellie-in-space",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Ellie in Space",
        "description": "Noticias espaciales semanales y análisis de la industria con perspectiva femenina y accesible.",
        "description_en": "Weekly space news and industry analysis with an accessible and approachable perspective.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@EllieinSpace",
        "youtube_handle": "@EllieinSpace",
        "content_format": ["video"],
        "topics": ["news", "SpaceX", "NASA", "launch"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "csi-starbase",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "CSI Starbase",
        "description": "Análisis técnico forense de los desarrollos de SpaceX Starbase: fotografías, documentos regulatorios y FCC.",
        "description_en": "Forensic technical analysis of SpaceX Starbase developments using photos, regulatory documents, and FCC filings.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@CSIStarbase",
        "youtube_handle": "@CSIStarbase",
        "content_format": ["video"],
        "topics": ["SpaceX", "Starship", "technical analysis", "regulatory"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "primal-space",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Primal Space",
        "description": "Historia y tecnología de la exploración espacial narrada con producción cinematográfica de alta calidad.",
        "description_en": "History and technology of space exploration narrated with high-quality cinematic production.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@PrimalSpace",
        "youtube_handle": "@PrimalSpace",
        "content_format": ["video"],
        "topics": ["history", "rockets", "exploration", "NASA"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "apogee",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Apogee",
        "description": "Documentales y divulgación sobre exploración espacial, historia astronáutica y misiones futuras.",
        "description_en": "Documentaries and science communication about space exploration, astronautical history, and future missions.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@ApogeeScience",
        "youtube_handle": "@ApogeeScience",
        "content_format": ["video"],
        "topics": ["exploration", "history", "NASA", "missions"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astrum",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Astrum",
        "description": "Tours visuales del sistema solar y el universo con imágenes reales de misiones espaciales.",
        "description_en": "Visual tours of the solar system and universe using real imagery from space missions.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@astrumspace",
        "youtube_handle": "@astrumspace",
        "content_format": ["video"],
        "topics": ["solar system", "planets", "astronomy", "missions"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "curious-droid",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Curious Droid",
        "description": "Historia y tecnología de la aviación, la exploración espacial y la ingeniería militar narradas con rigor.",
        "description_en": "History and technology of aviation, space exploration, and military engineering told with rigor.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@CuriousDroid",
        "youtube_handle": "@CuriousDroid",
        "content_format": ["video"],
        "topics": ["history", "aviation", "military", "space"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "answers-with-joe",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Answers with Joe",
        "description": "Joe Scott responde preguntas curiosas sobre ciencia, tecnología y el futuro con humor y accesibilidad.",
        "description_en": "Joe Scott answers curious questions about science, technology, and the future with humor and accessibility.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@AnswersWithJoe",
        "youtube_handle": "@AnswersWithJoe",
        "content_format": ["video", "podcast"],
        "topics": ["science", "technology", "futurism", "curiosity"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "kyle-hill",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Kyle Hill",
        "description": "Ciencia de la cultura pop: física, ingeniería y fenómenos del mundo real analizados con rigor y humor.",
        "description_en": "Pop culture science: physics, engineering, and real-world phenomena analyzed with rigor and humor.",
        "tagline": "Science says...",
        "tagline_en": "Science says...",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@KyleHill",
        "youtube_handle": "@KyleHill",
        "content_format": ["video"],
        "topics": ["physics", "pop culture", "engineering", "nuclear"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "sabine-hossenfelder",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "DE",
        "country_name": "Germany",
        "name": "Sabine Hossenfelder",
        "description": "Física teórica que critica el estado de la ciencia moderna y divulga física de partículas y cosmología.",
        "description_en": "Theoretical physicist who critiques modern science and communicates particle physics and cosmology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "avanzado",
        "website": "https://www.backreaction.blogspot.com",
        "youtube_url": "https://www.youtube.com/@SabineHossenfelder",
        "youtube_handle": "@SabineHossenfelder",
        "content_format": ["video", "article"],
        "topics": ["particle physics", "cosmology", "philosophy of science", "criticism"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "startalk",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "StarTalk",
        "description": "Neil deGrasse Tyson combina ciencia, cultura pop y entrevistas para acercar el cosmos al gran público.",
        "description_en": "Neil deGrasse Tyson combines science, pop culture, and interviews to bring the cosmos to a wide audience.",
        "tagline": "Science meets pop culture",
        "tagline_en": "Science meets pop culture",
        "rating": 5,
        "recommended": True,
        "difficulty": "general",
        "website": "https://www.startalkradio.net",
        "youtube_url": "https://www.youtube.com/@StarTalk",
        "youtube_handle": "@StarTalk",
        "content_format": ["video", "podcast"],
        "topics": ["cosmology", "astronomy", "pop culture", "interviews"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "event-horizon",
        "category": "youtube",
        "subcategory": "global",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Event Horizon",
        "description": "Entrevistas en profundidad con científicos y pensadores sobre cosmología, física y el futuro.",
        "description_en": "In-depth interviews with scientists and thinkers on cosmology, physics, and the future.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@EventHorizonShow",
        "youtube_handle": "@EventHorizonShow",
        "content_format": ["video", "interview"],
        "topics": ["cosmology", "physics", "interviews", "AI"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "dr-becky",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Dr. Becky",
        "description": "Astrofísica que divulga astronomía, agujeros negros y cosmología con autoridad y cercanía.",
        "description_en": "Astrophysicist communicating astronomy, black holes, and cosmology with authority and approachability.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@DrBecky",
        "youtube_handle": "@DrBecky",
        "content_format": ["video"],
        "topics": ["black holes", "galaxies", "cosmology", "JWST"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "dr-ben-miles",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Dr. Ben Miles",
        "description": "Ingeniero aeroespacial que explica propulsión, cohetes y la industria espacial con profundidad técnica.",
        "description_en": "Aerospace engineer explaining propulsion, rockets, and the space industry with technical depth.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@DrBenMiles",
        "youtube_handle": "@DrBenMiles",
        "content_format": ["video"],
        "topics": ["propulsion", "rockets", "engineering", "SpaceX"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "brian-keating",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Brian Keating",
        "description": "Cosmólogo experimental con entrevistas y divulgación sobre el universo primitivo, la inflación y la cosmología.",
        "description_en": "Experimental cosmologist with interviews and science communication on the early universe, inflation, and cosmology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "website": "https://www.briankeating.com",
        "youtube_url": "https://www.youtube.com/@DrBrianKeating",
        "youtube_handle": "@DrBrianKeating",
        "content_format": ["video", "podcast", "interview"],
        "topics": ["cosmology", "CMB", "early universe", "physics"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "minutephysics",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "MinutePhysics",
        "description": "Explicaciones animadas de física en pocos minutos, desde mecánica cuántica hasta relatividad.",
        "description_en": "Animated physics explanations in minutes, from quantum mechanics to relativity.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@minutephysics",
        "youtube_handle": "@minutephysics",
        "content_format": ["video"],
        "topics": ["physics", "quantum mechanics", "relativity", "animation"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "mark-rober",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Mark Rober",
        "description": "Ex-ingeniero de la NASA crea proyectos de ingeniería espectaculares para divulgar ciencia.",
        "description_en": "Former NASA engineer creates spectacular engineering projects to communicate science.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "general",
        "website": "https://www.markrober.com",
        "youtube_url": "https://www.youtube.com/@MarkRober",
        "youtube_handle": "@MarkRober",
        "content_format": ["video"],
        "topics": ["engineering", "science", "experiments", "NASA"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "science-asylum",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Science Asylum",
        "description": "Física cuántica y relatividad explicadas de forma irreverente y visual por Nick Lucid.",
        "description_en": "Quantum physics and relativity explained irreverently and visually by Nick Lucid.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@ScienceAsylum",
        "youtube_handle": "@ScienceAsylum",
        "content_format": ["video"],
        "topics": ["quantum physics", "relativity", "thermodynamics"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "kosmo",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Kosmo",
        "description": "Exploración visual e hipnótica del espacio: planetas, galaxias y el cosmos en impresionantes visualizaciones.",
        "description_en": "Visual and hypnotic exploration of space: planets, galaxies, and the cosmos in stunning visualizations.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@KosmoEN",
        "youtube_handle": "@KosmoEN",
        "content_format": ["video"],
        "topics": ["space", "visualization", "planets", "astronomy"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "history-of-the-universe",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "History of the Universe",
        "description": "Historia cronológica del universo desde el Big Bang hasta el futuro lejano, con narración y animaciones.",
        "description_en": "Chronological history of the universe from the Big Bang to the distant future, with narration and animations.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@HistoryoftheUniverse",
        "youtube_handle": "@HistoryoftheUniverse",
        "content_format": ["video"],
        "topics": ["cosmology", "Big Bang", "stellar evolution", "future"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "sciencephile-the-ai",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Sciencephile the AI",
        "description": "Divulgación sobre cosmología, tecnología y el futuro de la humanidad narrada por una voz IA.",
        "description_en": "Science communication about cosmology, technology, and the future of humanity narrated by an AI voice.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SciencephiletheAI",
        "youtube_handle": "@SciencephiletheAI",
        "content_format": ["video"],
        "topics": ["cosmology", "futurism", "technology"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "launch-pad-astronomy",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Launch Pad Astronomy",
        "description": "Astronomía observacional y cosmología explicada por un astrónomo aficionado con rigor y pasión.",
        "description_en": "Observational astronomy and cosmology explained by an amateur astronomer with rigor and passion.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@LaunchPadAstronomy",
        "youtube_handle": "@LaunchPadAstronomy",
        "content_format": ["video"],
        "topics": ["astronomy", "observational", "cosmology"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "spaceforce",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Spaceforce",
        "description": "Divulgación sobre exploración espacial, noticias y tecnología aeroespacial.",
        "description_en": "Science communication covering space exploration, news, and aerospace technology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 2,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SpaceforceYT",
        "youtube_handle": "@SpaceforceYT",
        "content_format": ["video"],
        "topics": ["space", "news", "exploration"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "smallstars",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "SmallStars",
        "description": "Cobertura de la industria de lanzadores pequeños: Rocket Lab, Relativity, ABL y otras startups espaciales.",
        "description_en": "Coverage of the small launch vehicle industry: Rocket Lab, Relativity, ABL, and other space startups.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@SmallStarsMedia",
        "youtube_handle": "@SmallStarsMedia",
        "content_format": ["video"],
        "topics": ["small launch", "startups", "Rocket Lab", "industry"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "tmro",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "TMRO",
        "description": "Magazine de noticias espaciales en formato livestream con entrevistas a expertos de la industria.",
        "description_en": "Space news magazine in livestream format featuring interviews with industry experts.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "website": "https://www.tmro.tv",
        "youtube_url": "https://www.youtube.com/@TMRO",
        "youtube_handle": "@TMRO",
        "content_format": ["video", "livestream", "interview"],
        "topics": ["news", "industry", "interviews", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "deep-astronomy",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Deep Astronomy",
        "description": "Astronomía profunda y cosmología con foco en el universo lejano, galaxias y el cosmos observable.",
        "description_en": "Deep astronomy and cosmology focusing on the distant universe, galaxies, and the observable cosmos.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@DeepAstronomy",
        "youtube_handle": "@DeepAstronomy",
        "content_format": ["video", "podcast"],
        "topics": ["astronomy", "galaxies", "cosmology", "JWST"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "ridddle",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Ridddle",
        "description": "Divulgación científica animada sobre astronomía, física y misterios del universo para público general.",
        "description_en": "Animated science communication about astronomy, physics, and mysteries of the universe for a general audience.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@Ridddle",
        "youtube_handle": "@Ridddle",
        "content_format": ["video"],
        "topics": ["astronomy", "physics", "mysteries", "space"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astrokirsten",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "AstroKirsten",
        "description": "Astrónoma que divulga astronomía observacional, curiosidades del cosmos y la vida en ciencia.",
        "description_en": "Astronomer communicating observational astronomy, cosmic curiosities, and life in science.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@AstroKirsten",
        "youtube_handle": "@AstroKirsten",
        "content_format": ["video"],
        "topics": ["astronomy", "observational", "stargazing"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "the-spacemaker",
        "category": "youtube",
        "subcategory": "industria",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "The Spacemaker",
        "description": "Análisis de la industria espacial comercial: contratos, empresas emergentes y estrategia del sector.",
        "description_en": "Analysis of the commercial space industry: contracts, emerging companies, and sector strategy.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@TheSpacemaker",
        "youtube_handle": "@TheSpacemaker",
        "content_format": ["video"],
        "topics": ["industry", "commercial space", "business", "startups"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "cosmosapiens",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "CosmoSapiens",
        "description": "Divulgación sobre exploración espacial humana, colonización y la expansión de la humanidad por el cosmos.",
        "description_en": "Science communication about human space exploration, colonization, and humanity's expansion into the cosmos.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@CosmoSapiens",
        "youtube_handle": "@CosmoSapiens",
        "content_format": ["video"],
        "topics": ["exploration", "colonization", "future", "Mars"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "v101-space",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "V101 Space",
        "description": "Divulgación sobre planetas, lunas y el sistema solar con gran producción visual y narración clara.",
        "description_en": "Science communication about planets, moons, and the solar system with great visuals and clear narration.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@V101Space",
        "youtube_handle": "@V101Space",
        "content_format": ["video"],
        "topics": ["planets", "solar system", "moons", "astronomy"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "science-time",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "global",
        "country_name": "Global",
        "name": "Science Time",
        "description": "Vídeos cortos de divulgación científica sobre física, astronomía y descubrimientos recientes.",
        "description_en": "Short science communication videos about physics, astronomy, and recent discoveries.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@ScienceTime24",
        "youtube_handle": "@ScienceTime24",
        "content_format": ["video"],
        "topics": ["science", "physics", "astronomy", "discoveries"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "spaced-out",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Spaced Out",
        "description": "Noticias y análisis del sector espacial con foco en SpaceX y la nueva carrera espacial.",
        "description_en": "Space industry news and analysis focused on SpaceX and the new space race.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SpacedOutShow",
        "youtube_handle": "@SpacedOutShow",
        "content_format": ["video"],
        "topics": ["SpaceX", "news", "industry"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "spacexcentric",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "SpaceXcentric",
        "description": "Noticias y cobertura detallada de SpaceX: lanzamientos, Starship y la misión a Marte.",
        "description_en": "Detailed news and coverage of SpaceX: launches, Starship, and the Mars mission.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SpaceXcentric",
        "youtube_handle": "@SpaceXcentric",
        "content_format": ["video"],
        "topics": ["SpaceX", "Starship", "news", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "eager-space",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Eager Space",
        "description": "Análisis técnico detallado de SpaceX, Starship y propulsión coheteril con enfoque ingenieril.",
        "description_en": "Detailed technical analysis of SpaceX, Starship, and rocket propulsion with an engineering focus.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@EagerSpace",
        "youtube_handle": "@EagerSpace",
        "content_format": ["video"],
        "topics": ["SpaceX", "Starship", "propulsion", "engineering", "Raptor"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "the-space-bucket",
        "category": "youtube",
        "subcategory": "industria",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "The Space Bucket",
        "description": "Cobertura de la industria espacial comercial: empresas emergentes, contratos y el ecosistema NewSpace.",
        "description_en": "Coverage of the commercial space industry: emerging companies, contracts, and the NewSpace ecosystem.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@TheSpaceBucket",
        "youtube_handle": "@TheSpaceBucket",
        "content_format": ["video"],
        "topics": ["industry", "NewSpace", "business", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "found-and-explained",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "AU",
        "country_name": "Australia",
        "name": "Found And Explained",
        "description": "Análisis técnico de propulsión, diseño de cohetes y misiones espaciales con rigor ingenieril.",
        "description_en": "Technical analysis of propulsion, rocket design, and space missions with engineering rigor.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@FoundAndExplained",
        "youtube_handle": "@FoundAndExplained",
        "content_format": ["video"],
        "topics": ["propulsion", "rockets", "engineering", "SpaceX"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "mustard",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Mustard",
        "description": "Historia de la aviación y la tecnología aeroespacial con animaciones 3D de extraordinaria calidad.",
        "description_en": "History of aviation and aerospace technology with extraordinarily high-quality 3D animations.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@MustardChannel",
        "youtube_handle": "@MustardChannel",
        "content_format": ["video"],
        "topics": ["aviation history", "aerospace", "military", "design"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "hazegrayart",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Hazegrayart",
        "description": "Visualizaciones 3D cinematográficas de buques de guerra, aviones y tecnología militar.",
        "description_en": "Cinematic 3D visualizations of warships, aircraft, and military technology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@hazegrayart",
        "youtube_handle": "@hazegrayart",
        "content_format": ["video"],
        "topics": ["military", "naval", "aviation", "visualization"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "jared-owen",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Jared Owen",
        "description": "Animaciones 3D que explican el funcionamiento interno de cohetes, aviones, edificios e ingenios complejos.",
        "description_en": "3D animations explaining the inner workings of rockets, planes, buildings, and complex machines.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@JaredOwen",
        "youtube_handle": "@JaredOwen",
        "content_format": ["video"],
        "topics": ["3D animation", "engineering", "rockets", "mechanisms"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "stand-up-maths",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Stand-up Maths",
        "description": "Matt Parker hace matemáticas divertidas: puzzles, errores matemáticos y maravillas numéricas.",
        "description_en": "Matt Parker makes mathematics fun: puzzles, mathematical errors, and numerical wonders.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@standupmaths",
        "youtube_handle": "@standupmaths",
        "content_format": ["video"],
        "topics": ["mathematics", "puzzles", "comedy", "numbers"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "numberphile",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Numberphile",
        "description": "Matemáticos de todo el mundo explican sus temas favoritos de manera accesible y fascinante.",
        "description_en": "Mathematicians from around the world explain their favorite topics in an accessible and fascinating way.",
        "tagline": "Videos about numbers",
        "tagline_en": "Videos about numbers",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "website": "https://www.numberphile.com",
        "youtube_url": "https://www.youtube.com/@numberphile",
        "youtube_handle": "@numberphile",
        "content_format": ["video"],
        "topics": ["mathematics", "number theory", "geometry", "interviews"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "up-and-atom",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "AU",
        "country_name": "Australia",
        "name": "Up and Atom",
        "description": "Jade Leonie explica física cuántica, matemáticas y ciencias de la computación de forma clara y visual.",
        "description_en": "Jade Leonie explains quantum physics, mathematics, and computer science in a clear and visual way.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@upandatom",
        "youtube_handle": "@upandatom",
        "content_format": ["video"],
        "topics": ["quantum physics", "mathematics", "computer science"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "domain-of-science",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Domain of Science",
        "description": "Mapas visuales del conocimiento científico: física, química, biología y matemáticas explicadas por un físico.",
        "description_en": "Visual maps of scientific knowledge: physics, chemistry, biology, and mathematics explained by a physicist.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@domainofscience",
        "youtube_handle": "@domainofscience",
        "content_format": ["video"],
        "topics": ["physics", "mathematics", "science maps", "overview"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "bps-space",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "BPS.space",
        "description": "Joe Barnard construye cohetes modelo con sistemas de control de vuelo y propulsión avanzados.",
        "description_en": "Joe Barnard builds model rockets with advanced flight control systems and propulsion.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "website": "https://www.bps.space",
        "youtube_url": "https://www.youtube.com/@BPSspace",
        "youtube_handle": "@BPSspace",
        "content_format": ["video"],
        "topics": ["model rockets", "engineering", "propulsion", "DIY"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "the-action-lab",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "The Action Lab",
        "description": "Experimentos científicos visuales sorprendentes que exploran física, química y materiales.",
        "description_en": "Surprising visual science experiments exploring physics, chemistry, and materials.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@TheActionLab",
        "youtube_handle": "@TheActionLab",
        "content_format": ["video"],
        "topics": ["experiments", "physics", "chemistry", "materials"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "steve-mould",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "GB",
        "country_name": "United Kingdom",
        "name": "Steve Mould",
        "description": "Ciencia visual y curiosa: física cotidiana, fluidos, electromagnetismo y fenómenos sorprendentes.",
        "description_en": "Visual and curious science: everyday physics, fluids, electromagnetism, and surprising phenomena.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SteveMould",
        "youtube_handle": "@SteveMould",
        "content_format": ["video"],
        "topics": ["physics", "fluids", "electromagnetism", "curiosities"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "nighthawkinlight",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "NightHawkInLight",
        "description": "Experimentos y proyectos DIY de ciencia aplicada: electrónica, plasma, química y energía.",
        "description_en": "DIY applied science experiments and projects: electronics, plasma, chemistry, and energy.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@NightHawkInLight",
        "youtube_handle": "@NightHawkInLight",
        "content_format": ["video"],
        "topics": ["DIY", "electronics", "chemistry", "plasma"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "codyslab",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Cody'sLab",
        "description": "Experimentos de química, minería y ciencia aplicada realizados con rigor y curiosidad.",
        "description_en": "Chemistry, mining, and applied science experiments carried out with rigor and curiosity.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@codyslab",
        "youtube_handle": "@codyslab",
        "content_format": ["video"],
        "topics": ["chemistry", "mining", "experiments", "DIY"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "applied-science",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Applied Science",
        "description": "Proyectos de ingeniería y ciencia aplicada de alto nivel técnico: óptica, electrónica, física experimental.",
        "description_en": "High-level technical engineering and applied science projects: optics, electronics, experimental physics.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "experto",
        "youtube_url": "https://www.youtube.com/@AppliedScience",
        "youtube_handle": "@AppliedScience",
        "content_format": ["video"],
        "topics": ["optics", "electronics", "physics", "engineering"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "nilered",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "CA",
        "country_name": "Canada",
        "name": "NileRed",
        "description": "Síntesis química y experimentos de laboratorio presentados con producción impecable y rigor científico.",
        "description_en": "Chemical synthesis and lab experiments presented with impeccable production and scientific rigor.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "website": "https://www.nilered.tv",
        "youtube_url": "https://www.youtube.com/@NileRed",
        "youtube_handle": "@NileRed",
        "content_format": ["video"],
        "topics": ["chemistry", "synthesis", "lab", "experiments"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "the-thought-emporium",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "CA",
        "country_name": "Canada",
        "name": "The Thought Emporium",
        "description": "Biología sintética, biohacking y ciencia experimental llevados al límite por un científico independiente.",
        "description_en": "Synthetic biology, biohacking, and experimental science pushed to the limits by an independent scientist.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@thethoughtemporium",
        "youtube_handle": "@thethoughtemporium",
        "content_format": ["video"],
        "topics": ["synthetic biology", "biohacking", "genetics", "chemistry"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "peter-sripol",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Peter Sripol",
        "description": "Construcción de aviones eléctricos caseros y ultraligeros con ingenio y humor.",
        "description_en": "Building DIY electric planes and ultralight aircraft with ingenuity and humor.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@PeterSripol",
        "youtube_handle": "@PeterSripol",
        "content_format": ["video"],
        "topics": ["aviation", "DIY", "electric aircraft", "engineering"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "rctestflight",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "rctestflight",
        "description": "Construcción y prueba de aviones y cohetes RC con tecnología y física aplicada.",
        "description_en": "Building and testing RC aircraft and rockets with applied technology and physics.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@rctestflight",
        "youtube_handle": "@rctestflight",
        "content_format": ["video"],
        "topics": ["RC aircraft", "DIY", "rockets", "engineering"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "the-everyday-explorer",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "The Everyday Explorer",
        "description": "Ciencia y exploración del mundo real: geología, biología y fenómenos naturales accesibles.",
        "description_en": "Science and real-world exploration: geology, biology, and accessible natural phenomena.",
        "tagline": "",
        "tagline_en": "",
        "rating": 2,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@TheEverydayExplorer",
        "youtube_handle": "@TheEverydayExplorer",
        "content_format": ["video"],
        "topics": ["geology", "biology", "exploration", "nature"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "space-news-pod",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Space News Pod",
        "description": "Podcast en vídeo con las últimas noticias del sector espacial en formato ágil y accesible.",
        "description_en": "Video podcast covering the latest space industry news in an agile and accessible format.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SpaceNewsPod",
        "youtube_handle": "@SpaceNewsPod",
        "content_format": ["video", "podcast"],
        "topics": ["news", "launches", "SpaceX", "NASA"],
        "featured": False,
        "is_free": True,
    },
 
    # ── SPANISH CHANNELS ──────────────────────────────────────────────────────
 
    {
        "slug": "quantum-fracture",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "QuantumFracture",
        "description": "José Luis Crespo explica física cuántica, relatividad y cosmología de manera rigurosa y apasionante.",
        "description_en": "José Luis Crespo explains quantum physics, relativity, and cosmology rigorously and passionately.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@QuantumFracture",
        "youtube_handle": "@QuantumFracture",
        "content_format": ["video"],
        "topics": ["quantum physics", "relativity", "cosmology", "particle physics"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "date-un-vlog",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Date un Vlog",
        "description": "Tecnología, ciencia e ingeniería explicadas de forma cercana, curiosa y con humor.",
        "description_en": "Technology, science, and engineering explained in a close, curious, and humorous way.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@DateUnVlog",
        "youtube_handle": "@DateUnVlog",
        "content_format": ["video"],
        "topics": ["technology", "science", "engineering", "curiosity"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "el-robot-de-platon",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "PE",
        "country_name": "Peru",
        "name": "El Robot de Platón",
        "description": "Física, matemáticas y filosofía de la ciencia explicadas con profundidad y rigor desde Perú.",
        "description_en": "Physics, mathematics, and philosophy of science explained with depth and rigor from Peru.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@ElRobotdePlaton",
        "youtube_handle": "@ElRobotdePlaton",
        "content_format": ["video"],
        "topics": ["physics", "mathematics", "philosophy", "cosmology"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "c-de-ciencia",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "C de Ciencia",
        "description": "Divulgación científica general en español: física, química, biología y curiosidades del universo.",
        "description_en": "General science communication in Spanish: physics, chemistry, biology, and curiosities of the universe.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@CdeCiencia",
        "youtube_handle": "@CdeCiencia",
        "content_format": ["video"],
        "topics": ["physics", "chemistry", "biology", "curiosity"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "la-gata-de-schrodinger",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "La Gata de Schrödinger",
        "description": "Física cuántica, astronomía y ciencia explicadas con rigor y perspectiva femenina.",
        "description_en": "Quantum physics, astronomy, and science explained with rigor and a female perspective.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@LaGatadeSchrodinger",
        "youtube_handle": "@LaGatadeSchrodinger",
        "content_format": ["video"],
        "topics": ["quantum physics", "astronomy", "science"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "ciencias-de-la-ciencia",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Ciencias de la Ciencia",
        "description": "Metaciencia, historia y filosofía de la ciencia: cómo funciona la investigación científica.",
        "description_en": "Metascience, history, and philosophy of science: how scientific research works.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@CienciasdelaCiencia",
        "youtube_handle": "@CienciasdelaCiencia",
        "content_format": ["video"],
        "topics": ["philosophy of science", "history", "methodology"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "control-de-mision",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Control de Misión",
        "description": "Noticias del sector espacial en español: lanzamientos, SpaceX, ESA y la industria global.",
        "description_en": "Space industry news in Spanish: launches, SpaceX, ESA, and the global industry.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@ControlDeMision",
        "youtube_handle": "@ControlDeMision",
        "content_format": ["video"],
        "topics": ["news", "SpaceX", "ESA", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "frontera-espacial",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Frontera Espacial",
        "description": "Noticias y análisis del sector espacial en español con foco en misiones y tecnología.",
        "description_en": "Space sector news and analysis in Spanish focused on missions and technology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@FronteraEspacial",
        "youtube_handle": "@FronteraEspacial",
        "content_format": ["video"],
        "topics": ["news", "missions", "technology", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "diario-de-un-astronomo",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Diario de un Astrónomo",
        "description": "Astronomía observacional y divulgación desde la perspectiva de un astrónomo profesional español.",
        "description_en": "Observational astronomy and science communication from the perspective of a Spanish professional astronomer.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@DiariodeunAstronomo",
        "youtube_handle": "@DiariodeunAstronomo",
        "content_format": ["video"],
        "topics": ["astronomy", "observational", "research", "stars"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "el-fisico-en-viaje",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "El físico en viaje",
        "description": "Física y ciencia explicadas con viajes, experimentos y situaciones cotidianas por un físico español.",
        "description_en": "Physics and science explained through travel, experiments, and everyday situations by a Spanish physicist.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@ElFisicoenViaje",
        "youtube_handle": "@ElFisicoenViaje",
        "content_format": ["video"],
        "topics": ["physics", "experiments", "travel", "education"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astronomia-web",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Astronomía Web",
        "description": "Divulgación astronómica en español: planetas, misiones, astrofísica y el universo observable.",
        "description_en": "Astronomical science communication in Spanish: planets, missions, astrophysics, and the observable universe.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@AstronomiaWeb",
        "youtube_handle": "@AstronomiaWeb",
        "content_format": ["video"],
        "topics": ["astronomy", "planets", "missions", "astrophysics"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astrocity",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Astrocity",
        "description": "Análisis técnico de cohetes, propulsión y la industria espacial en español con rigor ingenieril.",
        "description_en": "Technical analysis of rockets, propulsion, and the space industry in Spanish with engineering rigor.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "avanzado",
        "youtube_url": "https://www.youtube.com/@Astrocity",
        "youtube_handle": "@Astrocity",
        "content_format": ["video"],
        "topics": ["rockets", "propulsion", "engineering", "SpaceX"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "espacio-profundo",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Espacio Profundo",
        "description": "Cosmología, astronomía profunda y física del universo temprano divulgadas en castellano.",
        "description_en": "Cosmology, deep astronomy, and early universe physics communicated in Spanish.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@EspacioProfundo",
        "youtube_handle": "@EspacioProfundo",
        "content_format": ["video"],
        "topics": ["cosmology", "deep space", "early universe", "astronomy"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astrofisicos-en-accion",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "MX",
        "country_name": "Mexico",
        "name": "Astrofísicos en Acción",
        "description": "Divulgación astrofísica en español por investigadores mexicanos: galaxias, estrellas y cosmología.",
        "description_en": "Astrophysics science communication in Spanish by Mexican researchers: galaxies, stars, and cosmology.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@AstrofisicosEnAccion",
        "youtube_handle": "@AstrofisicosEnAccion",
        "content_format": ["video"],
        "topics": ["astrophysics", "galaxies", "stars", "research"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "unicoos",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Unicoos",
        "description": "Matemáticas y física para estudiantes de bachillerato y universidad; uno de los canales educativos más grandes de habla hispana.",
        "description_en": "Mathematics and physics for high school and university students; one of the largest Spanish-language educational channels.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "website": "https://www.unicoos.com",
        "youtube_url": "https://www.youtube.com/@unicoos",
        "youtube_handle": "@unicoos",
        "content_format": ["video", "article"],
        "topics": ["mathematics", "physics", "education", "bachillerato"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "todo-el-espacio",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Todo el Espacio",
        "description": "Resúmenes de noticias espaciales en español: lanzamientos, misiones y actualidad del sector.",
        "description_en": "Space news summaries in Spanish: launches, missions, and current events in the sector.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@TodoelEspacio",
        "youtube_handle": "@TodoelEspacio",
        "content_format": ["video"],
        "topics": ["news", "launches", "missions"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "kosmo-en-espanol",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "global",
        "country_name": "Global",
        "name": "Kosmo en Español",
        "description": "Versión en español del canal Kosmo: exploración visual del espacio, planetas y el universo.",
        "description_en": "Spanish version of the Kosmo channel: visual exploration of space, planets, and the universe.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@KosmoEspanol",
        "youtube_handle": "@KosmoEspanol",
        "content_format": ["video"],
        "topics": ["space", "visualization", "planets"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "ridddle-en-espanol",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "global",
        "country_name": "Global",
        "name": "Ridddle en Español",
        "description": "Versión en español del canal Ridddle: divulgación animada sobre astronomía y misterios del cosmos.",
        "description_en": "Spanish version of the Ridddle channel: animated science communication about astronomy and cosmic mysteries.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@RiddleEnEspanol",
        "youtube_handle": "@RiddleEnEspanol",
        "content_format": ["video"],
        "topics": ["astronomy", "mysteries", "space"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "universo-desconocido",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Universo Desconocido",
        "description": "Misterios del cosmos, fenómenos inexplicados y divulgación astronómica en castellano.",
        "description_en": "Mysteries of the cosmos, unexplained phenomena, and astronomical science communication in Spanish.",
        "tagline": "",
        "tagline_en": "",
        "rating": 2,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@UniversoDesconocido",
        "youtube_handle": "@UniversoDesconocido",
        "content_format": ["video"],
        "topics": ["mysteries", "astronomy", "cosmos"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "el-baul-de-los-conocimientos",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "El Baúl de los Conocimientos",
        "description": "Divulgación científica y tecnológica general en español: física, historia de la ciencia y curiosidades.",
        "description_en": "General science and technology communication in Spanish: physics, history of science, and curiosities.",
        "tagline": "",
        "tagline_en": "",
        "rating": 2,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@ElBauldelosConocimientos",
        "youtube_handle": "@ElBauldelosConocimientos",
        "content_format": ["video"],
        "topics": ["science", "technology", "history", "curiosity"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "robot-de-colon",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "PE",
        "country_name": "Peru",
        "name": "Robot de Colón",
        "description": "Historia, ciencia y exploración humana divulgadas desde Perú con perspectiva iberoamericana.",
        "description_en": "History, science, and human exploration communicated from Peru with an Ibero-American perspective.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@RobotdeColon",
        "youtube_handle": "@RobotdeColon",
        "content_format": ["video"],
        "topics": ["history", "science", "exploration"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "spacenoceros",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "SpaceNoceros",
        "description": "Divulgación espacial en español con humor y creatividad: cohetes, misiones y la nueva era espacial.",
        "description_en": "Space science communication in Spanish with humor and creativity: rockets, missions, and the new space age.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@SpaceNoceros",
        "youtube_handle": "@SpaceNoceros",
        "content_format": ["video"],
        "topics": ["space", "rockets", "missions", "humor"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "noticiero-espacial",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Noticiero Espacial",
        "description": "Boletín de noticias espaciales en español: lanzamientos, misiones y actualidad del sector aeroespacial.",
        "description_en": "Space news bulletin in Spanish: launches, missions, and current affairs in the aerospace sector.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@NoticieroEspacial",
        "youtube_handle": "@NoticieroEspacial",
        "content_format": ["video"],
        "topics": ["news", "launches", "missions"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "infoespacial",
        "category": "youtube",
        "subcategory": "noticias",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "InfoEspacial",
        "description": "Portal de noticias aeroespaciales en español con cobertura de la industria europea y global.",
        "description_en": "Aerospace news portal in Spanish covering the European and global industry.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "website": "https://www.infoespacial.com",
        "youtube_url": "https://www.youtube.com/@InfoEspacial",
        "youtube_handle": "@InfoEspacial",
        "content_format": ["video", "article"],
        "topics": ["news", "ESA", "industry", "launches"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "la-via-lactea",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "La Vía Láctea",
        "description": "Astronomía y astrofísica en español: galaxias, estrellas, agujeros negros y el universo profundo.",
        "description_en": "Astronomy and astrophysics in Spanish: galaxies, stars, black holes, and the deep universe.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@LaViaLactea",
        "youtube_handle": "@LaViaLactea",
        "content_format": ["video"],
        "topics": ["astronomy", "galaxies", "stars", "black holes"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "universo-resuelto",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Universo Resuelto",
        "description": "Preguntas sobre el universo respondidas con rigor científico y claridad en español.",
        "description_en": "Questions about the universe answered with scientific rigor and clarity in Spanish.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@UniversoResuelto",
        "youtube_handle": "@UniversoResuelto",
        "content_format": ["video"],
        "topics": ["astronomy", "physics", "curiosity", "cosmos"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "planeta-snob",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Planeta Snob",
        "description": "Ciencia, tecnología y cultura desde una perspectiva crítica, irónica y profunda en español.",
        "description_en": "Science, technology, and culture from a critical, ironic, and deep perspective in Spanish.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@PlanetaSnob",
        "youtube_handle": "@PlanetaSnob",
        "content_format": ["video"],
        "topics": ["science", "technology", "culture", "critical thinking"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "dot-csv",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "es",
        "country": "ES",
        "country_name": "Spain",
        "name": "Dot CSV",
        "description": "Carlos Santana divulga inteligencia artificial, machine learning y ciencia de datos de forma accesible.",
        "description_en": "Carlos Santana communicates artificial intelligence, machine learning, and data science accessibly.",
        "tagline": "",
        "tagline_en": "",
        "rating": 5,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@DotCSV",
        "youtube_handle": "@DotCSV",
        "content_format": ["video"],
        "topics": ["AI", "machine learning", "data science", "neural networks"],
        "featured": True,
        "is_free": True,
    },
    {
        "slug": "ringa-tech",
        "category": "youtube",
        "subcategory": "tecnico",
        "language": "es",
        "country": "MX",
        "country_name": "Mexico",
        "name": "Ringa Tech",
        "description": "Tecnología, programación e inteligencia artificial explicadas en español para principiantes y expertos.",
        "description_en": "Technology, programming, and artificial intelligence explained in Spanish for beginners and experts.",
        "tagline": "",
        "tagline_en": "",
        "rating": 4,
        "recommended": True,
        "difficulty": "intermedio",
        "youtube_url": "https://www.youtube.com/@RingaTech",
        "youtube_handle": "@RingaTech",
        "content_format": ["video"],
        "topics": ["technology", "programming", "AI", "tutorials"],
        "featured": False,
        "is_free": True,
    },
    {
        "slug": "astro-alexandra",
        "category": "youtube",
        "subcategory": "divulgacion",
        "language": "en",
        "country": "US",
        "country_name": "United States",
        "name": "Astro Alexandra",
        "description": "Astrónoma que divulga astronomía, astrofísica y la vida en la investigación científica.",
        "description_en": "Astronomer communicating astronomy, astrophysics, and life in scientific research.",
        "tagline": "",
        "tagline_en": "",
        "rating": 3,
        "recommended": False,
        "difficulty": "general",
        "youtube_url": "https://www.youtube.com/@AstroAlexandra",
        "youtube_handle": "@AstroAlexandra",
        "content_format": ["video"],
        "topics": ["astronomy", "astrophysics", "research", "women in science"],
        "featured": False,
        "is_free": True,
    },
]

        print(f"Seeding new media source records to {label}...")
        added_count = 0
        for item_data in media_data:
            if item_data["slug"] not in existing_slugs:
                item = models.MediaSource(**item_data)
                db.add(item)
                added_count += 1
        
        if added_count > 0:
            db.commit()
            print(f"Successfully added {added_count} new records to {label}.")
        else:
            print(f"No new records to add to {label}.")
            
    except Exception as e:
        print(f"Error seeding {label} data: {e}")
        if 'db' in locals():
            db.rollback()
    finally:
        if 'db' in locals():
            db.close()

if __name__ == "__main__":
    # Seed Remote
    seed_db(REMOTE_URL, "REMOTE")
    
    # Seed Local
    seed_db(LOCAL_URL, "LOCAL")
